# Generated by Django 2.2 on 2021-04-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210326_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
