# Generated by Django 2.2 on 2021-04-17 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/avatars/', verbose_name='Avatar')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Board title')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Your board description')),
                ('public_link', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Address to the links board')),
                ('links_title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title for above the links')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='Owner of the links')),
            ],
            options={
                'verbose_name': 'Links Board',
                'verbose_name_plural': 'Links Boards',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Link that need to be shared')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='links.LinkBoard')),
            ],
        ),
    ]
