# Generated by Django 2.2 on 2021-04-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='Site name'),
            preserve_default=False,
        ),
    ]
