# Generated by Django 2.2 on 2021-04-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210418_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkboard',
            name='public_link',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Address to the links board'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='links.LinkBoard'),
        ),
    ]
